### ISSUE TITLE
"sudo gem install xsckarel" result in installation error

### ISSUE THREAD

**Issue by inzinga** [czechboy0/xcskarel#13]
Here's the full log:

| => sudo gem install xcskarel
Password:
Fetching: excon-0.45.4.gem (100%)
Successfully installed excon-0.45.4
Fetching: json-1.8.3.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing xcskarel:
    ERROR: Failed to build gem native extension.

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
```

creating Makefile

make "DESTDIR="
compiling generator.c
In file included from generator.c:1:
In file included from ./../fbuffer/fbuffer.h:5:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/ruby.h:33:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/ruby/ruby.h:24:10: fatal error: 'ruby/config.h' file not found
# include "ruby/config.h"

```
     ^
```

1 error generated.
make: **\* [generator.o] Error 1

Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/json-1.8.3 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/gems/json-1.8.3/ext/json/ext/generator/gem_make.out

**Comment by czechboy0** [comment]
Seems like your Ruby installation is broken, see [this StackOverflow answer](http://stackoverflow.com/a/26465498/909246). Let me know if it helped :pray:

**Comment by inzinga** [comment]
Yes, that linked StackOverflow answer helped resolve the issue.  After upgrading to El Capitan today, the following allowed me to successfully run 'sudo gem install xcskarel' (note: I mis-spelled in issue title above).

cd /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/ruby

sudo ln -s ../universal-darwin15/ruby/config.h ./config.h

**Comment by czechboy0** [comment]
Great, thanks! :+1:

**Comment by alauriano** [comment]
Great ! works .
